<?php
// pages/ProductListPage/products-data.php

$products = [
    [
        "id"       => 1,
        "name"     => "Spanish Latte",
        "tagline"  => "Sweet, bold, and impossibly silky.",
        "price"    => 180,
        "category" => "Espresso",
        "badge"    => "Bestseller",
        "image"    => "assets/js/images/spanish-latte.jpg",
        "desc"     => "A rich double shot of espresso balanced with sweetened condensed milk and whole milk, creating a caramel-sweet, velvety cup that keeps you coming back.",
        "specs" => [
            ["icon" => "bi-thermometer-half", "label" => "Temperature", "value" => "Hot / Iced"],
            ["icon" => "bi-cup-straw",         "label" => "Base",        "value" => "Espresso"],
            ["icon" => "bi-droplet-half",      "label" => "Milk",        "value" => "Condensed + Whole"],
            ["icon" => "bi-lightning-charge",  "label" => "Caffeine",    "value" => "Medium–High"],
        ],
    
        
        "tags"     => ["Sweet", "Creamy", "Bold"],
        "calories" => "~240 kcal",
        "volume"   => "12 oz",
        "rating"   => 4.9,
        "reviews"  => 312,
        "emoji"    => "☕",
    ],
    [
        "id"       => 2,
        "name"     => "Matcha Latte",
        "tagline"  => "Earthy, calm, and beautifully green.",
        "price"    => 195,
        "category" => "Non-Espresso",
        "badge"    => "Fan Fave",
        "image"    => "assets/js/images/matcha-latte.jpg",
        "desc"     => "Ceremonial-grade Japanese matcha whisked smooth and layered over steamed oat milk. Subtle sweetness, grassy depth, and a calm clean finish.",
        "specs" => [
            ["icon" => "bi-thermometer-half", "label" => "Temperature", "value" => "Hot / Iced"],
            ["icon" => "bi-cup-straw",         "label" => "Base",        "value" => "Ceremonial Matcha"],
            ["icon" => "bi-droplet-half",      "label" => "Milk",        "value" => "Oat Milk"],
            ["icon" => "bi-lightning-charge",  "label" => "Caffeine",    "value" => "Low–Medium"],
        ],
        
        "tags"     => ["Earthy", "Smooth", "Calming"],
        "calories" => "~190 kcal",
        "volume"   => "12 oz",
        "rating"   => 4.8,
        "reviews"  => 204,
        "emoji"    => "🍵",
    ],
    [
        "id"       => 3,
        "name"     => "Ube Latte",
        "tagline"  => "Dreamy purple magic in a cup.",
        "price"    => 195,
        "category" => "Non-Espresso",
        "badge"    => "Local Pride",
        "image"    => "assets/js/images/ube-latte.webp",
        "desc"     => "Real ube halaya blended into steamed milk creates this gorgeous violet drink — gently sweet, subtly nutty, and unmistakably Filipino.",
        "specs" => [
            ["icon" => "bi-thermometer-half", "label" => "Temperature", "value" => "Hot / Iced"],
            ["icon" => "bi-cup-straw",         "label" => "Base",        "value" => "Ube Halaya"],
            ["icon" => "bi-droplet-half",      "label" => "Milk",        "value" => "Whole / Oat"],
            ["icon" => "bi-lightning-charge",  "label" => "Caffeine",    "value" => "Caffeine-Free"],
        ],
        
        "tags"     => ["Sweet", "Nutty", "Unique"],
        "calories" => "~210 kcal",
        "volume"   => "12 oz",
        "rating"   => 4.9,
        "reviews"  => 278,
        "emoji"    => "💜",
    ],
    [
        "id"       => 4,
        "name"     => "Iced Sea Salt",
        "tagline"  => "Cold, bold, and perfectly balanced.",
        "price"    => 170,
        "category" => "Cold Brew",
        "badge"    => "Refreshing",
        "image"    => "assets/js/images/iced-seasalt.webp",
        "desc"     => "Our house cold brew — steeped 24 hours — topped with a whisper of lightly salted cream that slowly folds into the coffee as you sip.",
        "specs" => [
            ["icon" => "bi-thermometer-half", "label" => "Temperature", "value" => "Iced Only"],
            ["icon" => "bi-cup-straw",         "label" => "Base",        "value" => "24hr Cold Brew"],
            ["icon" => "bi-droplet-half",      "label" => "Topping",     "value" => "Sea Salt Cream"],
            ["icon" => "bi-lightning-charge",  "label" => "Caffeine",    "value" => "High"],
        ],
        "tags"     => ["Bold", "Salty-Sweet", "Refreshing"],
        "calories" => "~160 kcal",
        "volume"   => "16 oz",  
        "rating"   => 4.7,
        "reviews"  => 189,
        "emoji"    => "🧊",
    ],
    [
        "id"       => 5,
        "name"     => "Caramel Macchiato",
        "tagline"  => "Layers of warmth in every sip.",
        "price"    => 185,
        "category" => "Espresso",
        "badge"    => "Classic",
        "image"    => "assets/js/images/caramel-macchiato.jpg",
        "desc"     => "Vanilla-infused milk, a bold espresso mark, and a generous drizzle of house caramel. Layered to look as good as it tastes.",
        "specs" => [
            ["icon" => "bi-thermometer-half", "label" => "Temperature", "value" => "Hot / Iced"],
            ["icon" => "bi-cup-straw",         "label" => "Base",        "value" => "Espresso"],
            ["icon" => "bi-droplet-half",      "label" => "Milk",        "value" => "Vanilla Whole Milk"],
            ["icon" => "bi-lightning-charge",  "label" => "Caffeine",    "value" => "Medium–High"],
        ],
        "tags"     => ["Sweet", "Layered", "Warm"],
        "calories" => "~250 kcal",
        "volume"   => "12 oz",
        "rating"   => 4.8,
        "reviews"  => 241,
        "emoji"    => "🍯",
    ],
];

$categories = ["All", "Espresso", "Non-Espresso", "Cold Brew"];
